import { Poppins } from "next/font/google";
import "./globals.css";
import StudyNookNavbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={poppins.className}
    >
      <body className="min-h-full flex flex-col">
        <header>
         <StudyNookNavbar></StudyNookNavbar>
        </header>
        <main>
          {children}
          <Toaster position="top-right" />
        </main>
        <footer>
          <Footer></Footer>
        </footer>
        </body>
    </html>
  );
}
